### ISSUE TITLE
Oczekiwałbym że funkcja find coś zwróci. Albo element albo iterator

### ISSUE THREAD

**Issue by ziobron** [bogkra/persons#3]
https://github.com/bogkra/persons/blob/624d33c74158cef58bcce9b5934c5a5f6d618cb1/main.cpp#L28

**Comment by bogkra** [comment]
zwraca bool. Ale oczywiście może iterator

**Comment by ziobron** [comment]
To jak zwraca bool to ignorujesz to w kodzie, bo nie sprawdzasz nigdzie co zostało zwrócone.

**Comment by bogkra** [comment]
to jest sprawdzane w środku funkcji:  if (it != m.end()) {
    cout << "Found Person:" << endl;
    (*it)->show();
  }
  else 
    cout << "PESEL not found!" << endl;

**Comment by bogkra** [comment]
chociaż eleganciej by pewnie było przez wyjątki albo w ogóle na zewnątrz, no ale tak to było napisane, że w środku

**Comment by bogkra** [comment]
w wymaganiach nie było czy i jak ma znalezienie być sprawdzone na zewnątrz funkcji...

**Comment by bogkra** [comment]
no i jeśli ma być sprawdzane np. w main.cpp, to trzeba by za każdym razem powtarzać reakcję, lepiej to umieścić w funkcji, oczywiście można stworzyć kolejną funkcję, pytanie tylko czy to nie przesada

**Comment by ziobron** [comment]
Ok, może tak naprawdę to o coś innego mi chodzi, ale jak macie sprawdzanie czy find rzeczywiście coś zwraca to ok. 
A to coś innego to ścisłe powiązanie waszego kodu ze strumieniem wyjściowym, czyli cout. Ale na razie nie rozpatrujemy tego jako coś poważnego. Będzie w przyszłości okazja żeby przemyśleć design programu. Możesz zamknąć to issue.
