### ISSUE TITLE
W repozytorium nie powinno być w ogóle zakomentowanego kodu.

### ISSUE THREAD

**Issue by ziobron** [bogkra/persons#8]
https://github.com/bogkra/persons/blob/624d33c74158cef58bcce9b5934c5a5f6d618cb1/functions.cpp#L211

Te dynamic_casty poza tym wyglądają niepokojąco i nie są potrzebne :) Na klasę bazową zawsze bez problemu można się rzutować.

**Comment by bogkra** [comment]
no nie wiem, próbowałem, ale nie dawało rady, może to wina tego, że miałem c++11 :D
