### ISSUE TITLE
Te wszystkie pola nie powinny być public. Powinny być private albo chociaż protected.

### ISSUE THREAD

**Issue by ziobron** [bogkra/persons#9]
https://github.com/bogkra/persons/blob/624d33c74158cef58bcce9b5934c5a5f6d618cb1/person.hpp#L15

**Comment by bogkra** [comment]
jeśli te pola nie będą public, to jak uzyskam dostęp np. w tej lambdzie? :

shared_ptr<Person>
Persons::findPersonPesel(string peselNumber)
{
  auto it = find_if(m.begin(), m.end(), [peselNumber] (const shared_ptr<Person> p) { return p->pesel == peselNumber;});
...

**Comment by ziobron** [comment]
Jak będą protected to nie będzie problemu. Ale w tej lambdzie tak naprawdę nie używasz niczego z klasy bazowej, więc spokojnie może być private.

**Comment by ziobron** [comment]
A już wiem, o m Ci chodzi. Zróbcie protected, to wystarczy

**Comment by bogkra** [comment]
Persons nie jest pochodną Person. Persons jest wektorem Person, nie dziedziczy po Person, więc protected nie wystarczy

**Comment by bogkra** [comment]
gettery porobione
